[package]
name = "master"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
derive_more = "0.99.17"
grb = "1.3.0"
itertools = "0.10.3"
ndarray = "0.15.4"