name: Generate Python libary documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download Gurobi
      run: wget -c https://packages.gurobi.com/9.5/gurobi9.5.1_linux64.tar.gz -O - | tar -xz
    - name: Set GUROBI_HOME
      run: export set GUROBI_HOME=gurobi951/linux64
    - name: Setup Python virtualenv
      run: virtualenv venv && source venv/bin/activate
    - name: Install master project using pip and maturin
      run: pip install .
    - name: Install pdocs
      run: pip install pydocs
    - name: Use pdocs to generate docs
      run: pdocs as_html master -o docs
