name: Generate Python libary documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Set GUROBI_HOME
      run: echo "GUROBI_HOME=${GITHUB_WORKSPACE}/gurobi912/linux64/" >> $GITHUB_ENV
    - name: Download Gurobi
      run: wget -c https://packages.gurobi.com/9.1/gurobi9.1.2_linux64.tar.gz -O - | tar -xz -C $GITHUB_WORKSPACE
    - name: Install master project using pip and maturin
      run: echo "GUROBI_HOME is $GUROBI_HOME [end]" && pip install .
    - name: Install pdocs
      run: pip install pydocs
    - name: Use pdocs to generate docs
      run: pdocs as_html master -o docs
